version: "3.9"

services:
  ollama:
    image: ollama/ollama:0.1.31
    hostname: ollama 
    container_name: ollama 
    restart: unless-stopped
    expose:
      - 11434
    deploy:
      resources:
      #   limits:
      #     cpus: '6'
      #     memory: 2048M
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU}"]
              capabilities: [gpu,video,compute,graphics,utility,compat32,display] 
    volumes:
      - /mnt/user/data/llm/ollama:/root/.ollama
    networks:
      ollama:
        ipv4_address: 172.28.0.2

  open-webui:
    image: ghcr.io/open-webui/open-webui
    hostname: open_webui
    container_name: open_webui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://172.28.0.2:11434
    expose:
      - 8080
    volumes:
      - /mnt/user/data/llm/webui:/app/backend/data
    networks:
      ollama:
        ipv4_address: 172.28.0.3

networks:
  ollama:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/17
